[settings]
experimental = true                      # TODO: Remove this
idiomatic_version_file_enable_tools = [] # TODO: Remove this

[tools]
# CLIs
"aqua:tummychow/git-absorb" = "latest"                                                        # Git utility for fixups # TODO: Add to official registry
"cargo:https://github.com/GitoxideLabs/gitoxide" = { version = "latest", crate = "gitoxide" } # VCS # TODO: Add to official registry
coreutils = "latest"                                                                          # Core utilities
just = "latest"                                                                               # Command runner
task = "latest"                                                                               # Command runner
chezmoi = "latest"                                                                            # Dotfile manager
zoxide = "latest"                                                                             # Change directory
eza = "latest"                                                                                # List files
bat = "latest"                                                                                # View files
bat-extras = "latest"                                                                         # View files
fd = "latest"                                                                                 # Find files
ripgrep = "latest"                                                                            # Search files
ripgrep-all = "latest"                                                                        # Search files
delta = "latest"                                                                              # Compare files
difftastic = "latest"                                                                         # Compare files
"aqua:chmln/sd" = "latest"                                                                    # Search and replace files # TODO: Add to official registry
"aqua:ms-jpq/sad" = "latest"                                                                  # Search and replace files
"cargo:choose" = "latest"                                                                     # Extract text from files # TODO: Add to official registry
"cargo:https://github.com/aaronriekenberg/rust-parallel" = "latest"                           # Parse arguments and execute commands # TODO: Add to official registry
"aqua:boyter/scc" = "latest"                                                                  # Code counter
tokei = "latest"                                                                              # Code counter
hyperfine = "latest"                                                                          # Benchmarking
"cargo:https://github.com/Nukesor/pueue" = "latest"                                           # Background task executor # TODO: Add to official registry
watchexec = "latest"                                                                          # File watcher
grex = "latest"                                                                               # Generate regular expressions
"aqua:tealdeer-rs/tealdeer" = "latest"                                                        # Cheatsheets # TODO: Add to official registry
cheat = "latest"                                                                              # Cheatsheets
"cargo:denisidoro/navi" = "latest"                                                            # Cheatsheets # TODO: Add to official registry
"aqua:ouch-org/ouch" = "latest"                                                               # Compress and decompress files # TODO: Add to official registry
dust = "latest"                                                                               # View disk usage
dua = "latest"                                                                                # View disk usage
gdu = "latest"                                                                                # View disk usage
"aqua:solidiquis/erdtree" = "latest"                                                          # View disk usage
duf = "latest"                                                                                # View disk usage
"cargo:https://github.com/Canop/dysk" = "latest"                                              # View disk usage
"aqua:dalance/procs" = "latest"                                                               # View running processes
"aqua:ericchiang/pup" = "latest"                                                              # HTML toolkit # TODO: Add to official registry
"go:github.com/sibprogrammer/xq" = "latest"                                                   # XML and HTML toolkit # TODO: Add to official registry
"cargo:https://github.com/medialab/xan" = "latest"                                            # CSV toolkit # TODO: Add to official registry
"aqua:01mf02/jaq" = "latest"                                                                  # JSON toolkit # TODO: Add to official registry
gojq = "latest"                                                                               # JSON toolkit
taplo = "latest"                                                                              # TOML toolkit
yq = "latest"                                                                                 # JSON, TOML, YAML, XML and CSV toolkit
dasel = "latest"                                                                              # JSON, TOML, YAML, XML and CSV toolkit
qsv = "latest"                                                                                # Data wrangling toolkit
"cargo:https://github.com/houseabsolute/precious" = "latest"                                  # Linter and formatter # TODO: Add to official registry
dprint = "latest"                                                                             # Formatter
"aqua:numtide/treefmt" = "latest"                                                             # Formatter # TODO: Add to official registry
lefthook = "latest"                                                                           # Git hook manager
age = "latest"                                                                                # Encryption
"aqua:str4d/rage" = "latest"                                                                  # Encryption # TODO: Add to official registry
"cargo:https://github.com/jedisct1/rsign2" = "latest"                                         # Signing # TODO: Add to official registry
sops = "latest"                                                                               # Configuration file encryption
"cargo:https://github.com/gibbz00/rops" = { version = "latest", crate = "rops-cli" }          # Configuration file encryption # TODO: Add to official registry
xh = "latest"                                                                                 # HTTP client
curlie = "latest"                                                                             # HTTP client
httpie-go = "latest"                                                                          # HTTP client
grpcurl = "latest"                                                                            # gRPC client
"aqua:fatedier/frp" = "latest"                                                                # Expose local web server to internet # TODO: Add to official registry
"aqua:openziti/zrok" = "latest"                                                               # Expose local web server to internet # TODO: Add to official registry
github-cli = "latest"                                                                         # GitHub client
helm = "latest"                                                                               # Kubernetes package manager
stern = "latest"                                                                              # Kubernetes log explorer
kubectx = "latest"                                                                            # Kubernetes context manager
kubens = "latest"                                                                             # Kubernetes namespace manager
jq = "latest"                                                                                 # JSON toolkit # TODO: Remove this
prettier = "latest"                                                                           # Formatter # TODO: Remove this
pre-commit = "latest"                                                                         # Git hook manager # TODO: Remove this
typst = "latest"                                                                              # Markdown based typesetting system
"npm:@mermaid-js/mermaid-cli" = "latest"                                                      # Diagram as code # TODO: Add to official registry
podman = "latest"                                                                             # Containerization
"pipx:containers/podman-compose" = "latest"                                                   # Containerization
docker-cli = "latest"                                                                         # Containerization
kubectl = "latest"                                                                            # Container orchestration
pulumi = "latest"                                                                             # Infrastructure as code
opentofu = "latest"                                                                           # Infrastructure as code
terragrunt = "latest"                                                                         # Infrastructure as code
kubergrunt = "latest"                                                                         # Kubernetes integration with Helm and Terraform # TODO: Remove this

# TUIs
fzf = "latest"                                   # Fuzzy finder
"aqua:skim-rs/skim" = "latest"                   # Fuzzy finder # TODO: Add to official registry
"go:github.com/akavel/up" = "latest"             # Utility for writing pipes # TODO: Add to official registry
lazygit = "latest"                               # Git client
gitui = "latest"                                 # Git client
zellij = "latest"                                # Terminal multiplexer
bottom = "latest"                                # System monitor
"aqua:bvaisvil/zenith" = "latest"                # System monitor # TODO: Add to official registry
"aqua:xxxserxxx/gotop" = "latest"                # System monitor # TODO: Add to official registry
neovim = "latest"                                # Text editor
"go:github.com/containers/podman-tui" = "latest" # Podman client
lazydocker = "latest"                            # Docker client
k9s = "latest"                                   # Kubernetes client

# Shell utilities
"cargo:https://github.com/rossmacarthur/sheldon" = "latest"                                    # Plugin manager # TODO: Add to official registry
starship = "latest"                                                                            # Prompt
"aqua:atuinsh/atuin" = "latest"                                                                # History
"aqua:carapace-sh/carapace-bin" = "latest"                                                     # Autocompletion # TODO: Add to official registry
"cargo:https://github.com/iffse/pay-respects" = { version = "latest", crate = "pay-respects" } # Autocorrection # TODO: Add to official registry
direnv = "latest"                                                                              # Environment manager

# LLM utilities
ollama = "latest" # Run servers locally

# Nushell
"cargo:https://github.com/nushell/nufmt" = "latest" # Formatter # TODO: Add to official registry

# Zsh and Bash
"npm:bash-language-server" = "latest" # Language server # TODO: Add to official registry
shellcheck = "latest"                 # Linter # TODO: Install shellharden as well
shfmt = "latest"                      # Formatter

# Lua
lua-language-server = "latest" # Language server
stylua = "latest"              # Formatter

# Haskell
haskell = "latest" # Toolchain and package manager

# Common Lisp
# sbcl = "latest" # Toolchain # TODO: Enable this

# Zig
zig = "latest" # Toolchain

# Rust
rust = { version = "latest", components = "rust-analyzer" } # Toolchain, package manager, language server, linter and formatter
cargo-binstall = "latest"                                   # Binary installer

# Racket
# racket = "latest" # Toolchain # TODO: Enable this

# Go
go = "latest"                                     # Toolchain and package manager
"go:golang.org/x/tools/gopls" = "latest"          # Language server # TODO: Add to official registry
staticcheck = "latest"                            # Linter
gofumpt = "latest"                                # Formatter
"go:github.com/go-delve/delve/cmd/dlv" = "latest" # Debugger # TODO: Add to official registry

# Java
java = "latest" # Toolchain

# Scala
scala = "latest" # Toolchain
sbt = "latest"   # Package manager

# Clojure
clojure = "latest" # Toolchain
