set shell := ["bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-o", "xtrace", "-c"]
set script-interpreter := ["bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-o", "xtrace", "-c"]

mod chezmoi
mod mise

# Install Just
init:
    curl --fail --silent --location --show-error https://just.systems/install.sh | bash -s -- --to=~/.local/bin
