[formula]
# Shells
nushell = {}
elvish = {}
fish = {}
zsh = {}
bash = {}

# CLIs
chezmoi = {}          # Dotfile manager
mise = {}             # Version manager
keychain = {}         # Key manager
gitoxide = {}         # Version control system
uutils-coreutils = {} # Core utilities
uutils-findutils = {} # Find utilities
uutils-diffutils = {} # Diff utilities
zoxide = {}           # Change directory
eza = {}              # List files
bat = {}              # View files
fd = {}               # Find files
ripgrep = {}          # Search files
difftastic = {}       # Compare files
delta = {}            # Compare files
git-absorb = {}       # Git utility for fixups
sd = {}               # Search and replace files
sad = {}              # Search and replace files
choose = {}           # Extract text from files
scc = {}              # Code counter
tokei = {}            # Code counter
just = {}             # Command runner
go-task = {}          # Command runner
hyperfine = {}        # Benchmarking
grex = {}             # Generate regular expressions
ouch = {}             # Compressor
pup = {}              # HTML toolkit
xq = {}               # XML and HTML toolkit
xan = {}              # CSV toolkit
jaq = {}              # JSON toolkit
gojq = {}             # JSON toolkit
taplo = {}            # TOML toolkit
yq = {}               # JSON, TOML, YAML, XML and CSV toolkit
dasel = {}            # JSON, TOML, YAML, XML and CSV toolkit
qsv = {}              # Data wrangling toolkit
watchexec = {}        # File watcher
pueue = {}            # Background task executor
rust-parallel = {}    # Parse arguments and execute commands
precious = {}         # Linter and formatter
dprint = {}           # Formatter
treefmt = {}          # Formatter
# devenv = {}           # Project manager # TODO: Enable this
lefthook = {} # Git hook manager
age = {}      # Encryption
rage = {}     # Encryption
# rsign2 = {}           # Signing # TODO: Enable this
sops = {} # Configuration file encryption
# rops = {}             # Configuration file encryption # TODO: Enable this
xh = {}         # HTTP client
curlie = {}     # HTTP client
grpcurl = {}    # gRPC client
nginx = {}      # Web server and reverse proxy
frpc = {}       # Expose local web server to internet
zrok = {}       # Expose local web server to internet
gh = {}         # GitHub client
awscli = {}     # AWS client
azure-cli = {}  # Azure client
ykman = {}      # YubiKey client
stern = {}      # Kubernetes log explorer
kubectx = {}    # Kubernetes context and namespace manager
git = {}        # VCS # TODO: Remove this
grep = {}       # Search files # TODO: Remove this
make = {}       # Build system # TODO: Remove this
gnupg = {}      # Encryption and signing # TODO: Remove this
jq = {}         # JSON toolkit # TODO: Remove this
prettier = {}   # Formatter # TODO: Remove this
entr = {}       # File watcher # TODO: Remove this
watchman = {}   # File watcher # TODO: Remove this
pre-commit = {} # Git hook manager # TODO: Remove this
minisign = {}   # Signing # TODO: Remove this
httpie = {}     # HTTP client # TODO: Remove this
wget = {}       # HTTP client # TODO: Remove this
curl = {}       # HTTP client # TODO: Remove this
graphqurl = {}  # GraphQL client # TODO: Remove this
mas = {}        # MacOS App Store application installer
kubergrunt = {} # Kubernetes integration with Helm and Terraform # TODO: Remove this
gettext = {}    # Internationalization and localization # TODO: Remove this

[cask]
# Keymaps
karabiner-elements = {}

# CLIs
ngrok = {}            # Expose local web server to internet
google-cloud-sdk = {} # Google Cloud client
