# TODO: Remove these once merged to upstream
tap = [
  "timescam/tap", # Pay-respects
]

[formula]
# Shells
nushell = {}
elvish = {}
fish = {}
zsh = {}
bash = {}

# CLIs
chezmoi = {}          # Dotfile manager
mise = {}             # Version manager
keychain = {}         # Key manager
gitoxide = {}         # Version control system
uutils-coreutils = {} # Core utilities
uutils-findutils = {} # Find utilities
uutils-diffutils = {} # Diff utilities
zoxide = {}           # Change directory
eza = {}              # List files
bat = {}              # View files
fd = {}               # Find files
ripgrep = {}          # Search files
difftastic = {}       # Compare files
delta = {}            # Compare files
git-absorb = {}       # Git utility for fixups
sd = {}               # Search and replace files
sad = {}              # Search and replace files
choose = {}           # Extract text from files
scc = {}              # Code counter
tokei = {}            # Code counter
just = {}             # Command runner
go-task = {}          # Command runner
hyperfine = {}        # Benchmarking
grex = {}             # Generate regular expressions
ouch = {}             # Compressor
pup = {}              # HTML toolkit
xq = {}               # XML and HTML toolkit
xan = {}              # CSV toolkit
jaq = {}              # JSON toolkit
gojq = {}             # JSON toolkit
taplo = {}            # TOML toolkit
yq = {}               # JSON, TOML, YAML, XML and CSV toolkit
dasel = {}            # JSON, TOML, YAML, XML and CSV toolkit
qsv = {}              # Data wrangling toolkit
watchexec = {}        # File watcher
pueue = {}            # Background task executor
rust-parallel = {}    # Parse arguments and execute commands
precious = {}         # Linter and formatter
dprint = {}           # Formatter
treefmt = {}          # Formatter
# devenv = {}           # Project manager # TODO: Enable this
lefthook = {} # Git hook manager
age = {}      # Encryption
rage = {}     # Encryption
# rsign2 = {}           # Signing # TODO: Enable this
sops = {} # Configuration file encryption
# rops = {}             # Configuration file encryption # TODO: Enable this
xh = {}         # HTTP client
curlie = {}     # HTTP client
grpcurl = {}    # gRPC client
nginx = {}      # Web server and reverse proxy
frpc = {}       # Expose local web server to internet
zrok = {}       # Expose local web server to internet
gh = {}         # GitHub client
awscli = {}     # AWS client
azure-cli = {}  # Azure client
ykman = {}      # YubiKey client
stern = {}      # Kubernetes log explorer
kubectx = {}    # Kubernetes context and namespace manager
git = {}        # VCS # TODO: Remove this
grep = {}       # Search files # TODO: Remove this
make = {}       # Build system # TODO: Remove this
gnupg = {}      # Encryption and signing # TODO: Remove this
jq = {}         # JSON toolkit # TODO: Remove this
prettier = {}   # Formatter # TODO: Remove this
entr = {}       # File watcher # TODO: Remove this
watchman = {}   # File watcher # TODO: Remove this
pre-commit = {} # Git hook manager # TODO: Remove this
minisign = {}   # Signing # TODO: Remove this
httpie = {}     # HTTP client # TODO: Remove this
wget = {}       # HTTP client # TODO: Remove this
curl = {}       # HTTP client # TODO: Remove this
graphqurl = {}  # GraphQL client # TODO: Remove this
mas = {}        # MacOS App Store application installer
kubergrunt = {} # Kubernetes integration with Helm and Terraform # TODO: Remove this
gettext = {}    # Internationalization and localization # TODO: Remove this

# TUIs
fzf = {}     # Fuzzy finder
sk = {}      # Fuzzy finder
up = {}      # Utility for writing pipes
lazygit = {} # Git client
gitui = {}   # Git client
forgit = {}  # Git client
zellij = {}  # Terminal multiplexer
neovim = {}  # Text editor
k9s = {}     # Kubernetes client

# GUIs
pinentry-mac = {} # Passphrase dialog

[cask]
# Keymaps
karabiner-elements = {}

# CLIs
ngrok = {}            # Expose local web server to internet
google-cloud-sdk = {} # Google Cloud client

# GUIs
"firefox@developer-edition" = {}             # Browser
brave-browser = {}                           # Browser
firefox = {}                                 # Browser
zen = {}                                     # Browser
alacritty = {}                               # Terminal
wezterm = {}                                 # Terminal
iterm2 = {}                                  # Terminal
emacs = {}                                   # Text editor
zed = {}                                     # Text editor
vscodium = {}                                # Text editor
void = {}                                    # Text editor
logseq = {}                                  # Note taker
element = {}                                 # Instant messenger
signal = {}                                  # Instant messenger
keybase = {}                                 # Instant messenger
bitwarden = {}                               # Password manager
proton-pass = {}                             # Password manager
proton-mail = {}                             # Mail
insomnia = {}                                # API client
dbeaver-community = {}                       # DB client
proton-drive = {}                            # Cloud storage
protonvpn = {}                               # VPN
mockoon = {}                                 # Mock server
raycast = {}                                 # Application launcher
thebrowsercompany-dia = { arch = "aarch64" } # Browser # TODO: Remove arch restriction
arc = {}                                     # Browser
google-chrome = {}                           # Browser
warp = {}                                    # Terminal
visual-studio-code = {}                      # Text editor
obsidian = {}                                # Note taker
notion = {}                                  # Note taker
microsoft-onenote = {}                       # Note taker
cursor = {}                                  # Text editor
windsurf = {}                                # Text editor
discord = {}                                 # Instant messenger
slack = {}                                   # Instant messenger
microsoft-teams = {}                         # Instant messenger
1password = {}                               # Password manager
readdle-spark = {}                           # Mail
notion-mail = {}                             # Mail
notion-calendar = {}                         # Calendar
microsoft-outlook = {}                       # Mail
ticktick = {}                                # Reminder
linear-linear = {}                           # Issue tracker
zoom = {}                                    # Video caller
postman = {}                                 # API client
tableplus = {}                               # DB client
dropbox = {}                                 # Cloud storage
nordvpn = {}                                 # VPN
figma = {}                                   # Design
microsoft-word = {}                          # Word processing
microsoft-excel = {}                         # Spreadsheet
microsoft-powerpoint = {}                    # Presentation
gitkraken = {}                               # Git client
docker = {}                                  # Containerization
yubico-authenticator = {}                    # TOTP generator
goland = {}                                  # IDE
chatgpt = { arch = "aarch64" }               # GenAI # TODO: Remove arch restriction
claude = {}                                  # GenAI

# TODO: Move these to casks
[mas]
# GUIs
Saber = { id = 1671523739 }                      # Handwritten note taker
Number = { id = 409203825 }                      # Spreadsheet
Pages = { id = 409201541 }                       # Word processing
Keynote = { id = 409183694 }                     # Presentation
Goodnotes = { id = 1444383602 }                  # Handwritten note taker
Notability = { id = 360593530 }                  # Handwritten note taker
"Perplexity: Ask Anything" = { id = 6714467650 } # GenAI
