[settings]
experimental = true                      # TODO: Remove this
idiomatic_version_file_enable_tools = [] # TODO: Remove this

[tools]
# Nushell
"cargo:https://github.com/nushell/nufmt" = {} # Formatter # TODO: Add to official registry

# Zsh and Bash
"npm:bash-language-server" = {} # Language server # TODO: Add to official registry
shellcheck = {}                 # Linter # TODO: Install shellharden as well
shfmt = {}                      # Formatter

# Lua
lua-language-server = {} # Language server
stylua = {}              # Formatter

# Haskell
haskell = {} # Toolchain and package manager

# Common Lisp
# sbcl = {} # Toolchain # TODO: Enable this

# Zig
zig = {} # Toolchain

# Rust
rust = { components = "rust-analyzer" } # Toolchain, package manager, language server, linter and formatter

# Racket
# racket = {} # Toolchain # TODO: Enable this

# Go
go = {}                                     # Toolchain and package manager
"go:golang.org/x/tools/gopls" = {}          # Language server # TODO: Add to official registry
staticcheck = {}                            # Linter
gofumpt = {}                                # Formatter
"go:github.com/go-delve/delve/cmd/dlv" = {} # Debugger # TODO: Add to official registry

# Java
java = {} # Toolchain

# Scala
scala = {} # Toolchain
sbt = {}   # Package manager
